# Codecov configuration

coverage:
  precision: 1
  round: down
  status:
    project:
      default:
        target: 84%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
